# This is default and very simple configuration file for Yasb.
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
bars:
  primary-bar:
    dimensions:
      height: 30
    padding:
      top: 0
      bottom: 0
    widgets:
      left: [
        "glazewm_workspaces",
        "active_window",
      ]
      right: [
        "cpu",
        "memory",
        "disk",
        "volume",
        "battery",
        "glazewm_tiling_direction",
        "clock",
      ]
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
      callbacks:
        on_left: "do_nothing"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "CPU: {info[percent][total]}%"
      update_interval: 1000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "do_nothing"
        on_right: "exec cmd /c Taskmgr"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "RAM: {virtual_mem_used} / {virtual_mem_total}"
      update_interval: 1000
      callbacks:
        on_left: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "Disk: {space[used][gb]} / {space[total][gb]}"
        volume_label: "C"
        update_interval: 60
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: true
          blur: True
          round_corners: True
          round_corners_type: "small"
          border_color: "System"
          alignment: "right"
          direction: "down"
        callbacks:
          on_left: "toggle_group"
          on_middle: "toggle_label"
          on_right: "exec explorer C:\\" # Open disk C in file explorer
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{icon} {level}"
      volume_icons:
        - "Vol:"  # Icon for muted
        - "Vol:"  # Icon for 0-10% volume
        - "Vol:"  # Icon for 11-30% volume
        - "Vol:"  # Icon for 31-60% volume
        - "Vol:"  # Icon for 61-100% volume
      audio_menu:
        blur: True
        round_corners: true
        round_corners_type: 'small'
        border_color: 'System'
        alignment: 'right'
        direction: 'down'
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon} {percent}%"
      update_interval: 1000
      charging_options:
        icon_format: "{icon}"
      status_icons:
        icon_charging: "Bat (charging):"
        icon_critical: "Bat:"
        icon_low: "Bat:"
        icon_medium: "Bat:"
        icon_high: "Bat:"
        icon_full: "Bat:"
      callbacks:
        on_left: "do_nothing"
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "|"
      vertical_label: "─"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%Y-%m-%d %a %H:%M:%S}"
      locale: ""
      update_interval: 1000
      timezones: []
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "next_timezone"
