# Reference: https://github.com/i3/i3/blob/next/etc/config


start-at-login = true

# Run Sketchybar and JankyBorders together with AeroSpace
after-startup-command = [
    # sketchbar has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget sketchybar',

    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change'
]

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Alacritty"
#     do script
#     activate
# end tell'
# '''
alt-enter = 'exec-and-forget open -n /Applications/Alacritty.app'

# i3 wraps focus by default
alt-h =         'focus --boundaries-action wrap-around-the-workspace left'
alt-j =         'focus --boundaries-action wrap-around-the-workspace down'
alt-k =         'focus --boundaries-action wrap-around-the-workspace up'
alt-l =         'focus --boundaries-action wrap-around-the-workspace right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-v = 'split horizontal'
alt-b = 'split vertical'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
# alt-0 = 'workspace 10'
# TODO: Need fix `alt-n` to keep same hehaviour with i3.
# Ref: https://github.com/nikitabobko/AeroSpace/pull/118
# Bug: alt-p cannot jump back when a workspae is empty
# alt-n = "exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace next || aerospace workspace $(aerospace list-workspaces --monitor focused --empty no | head -n 1)"
# alt-p = "exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace prev || aerospace workspace $(aerospace list-workspaces --monitor focused --empty no | tail -n 1)"
alt-n = 'workspace next'
alt-p = 'workspace prev'

alt-shift-1 = 'exec-and-forget aerospace move-node-to-workspace 1 && aerospace workspace 1'
alt-shift-2 = 'exec-and-forget aerospace move-node-to-workspace 2 && aerospace workspace 2'
alt-shift-3 = 'exec-and-forget aerospace move-node-to-workspace 3 && aerospace workspace 3'
alt-shift-4 = 'exec-and-forget aerospace move-node-to-workspace 4 && aerospace workspace 4'
alt-shift-5 = 'exec-and-forget aerospace move-node-to-workspace 5 && aerospace workspace 5'
alt-shift-6 = 'exec-and-forget aerospace move-node-to-workspace 6 && aerospace workspace 6'
alt-shift-7 = 'exec-and-forget aerospace move-node-to-workspace 7 && aerospace workspace 7'
alt-shift-8 = 'exec-and-forget aerospace move-node-to-workspace 8 && aerospace workspace 8'
alt-shift-9 = 'exec-and-forget aerospace move-node-to-workspace 9 && aerospace workspace 9'
# alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-shift-q = 'close --quit-if-last-window'

alt-tab = 'workspace-back-and-forth'

# alt-r = 'mode resize'
#
# [mode.resize.binding]
# h = 'resize width -50'
# j = 'resize height +50'
# k = 'resize height -50'
# l = 'resize width +50'
# enter = 'mode main'
# esc = 'mode main'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# Ref: https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback
[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = 'layout floating'
[[on-window-detected]]
# For matplotlib's preview configuration tool.
if.window-title-regex-substring = 'Subplot configuration tool'
run = 'layout floating'
